---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: windows-os-base
    image: windows-local/windows-os-base:latest
    dockerfile: Dockerfile.j2
    pull: False
    docker_host: tcp://localhost:2375
    command: ping -t localhost
    #networks:
    #  - name: molecule-network
    #    ipv4_address: 172.18.0.22
    #network_mode: nat
    #purge_networks: yes
provisioner:
  name: ansible
  inventory:
    host_vars:
      windows-os-base:
        ansible_user: Administrator
        ansible_password: Password123
        ansible_connection: winrm
        ansible_winrm_transport: basic
        ansible_winrm_server_cert_validation: ignore
        ansible_shell_type: powershell
verifier:
  name: ansible
